### PR TITLE
Bump Nextcloud version to 13

### PR DESCRIPTION
**Pull request by Eisfunke**
Change the max allowed version of Nextcloud to make it work with 13.
I tried it on my Nextcloud 13 Beta 3, no problems so far.

### CODE REVIEW

**Comment by violoncelloch** [comment]
could this be merged for the final release of nextcloud 13?

**Comment by tilosp** [comment]
@westberliner please merge

**Comment by westberliner** [comment]
Sry, got the message now. Should check my mailsettings. I'll create a release today.

**Comment by violoncelloch** [comment]
Thank you!

**Comment by westberliner** [comment]
Sorry, for waiting so long. Just released it on apps.nextcloud.com.

**Comment by violoncelloch** [comment]
No problem... It's still on time for the final release of nc13...

**Comment by westberliner** [comment]
And now I found the right settings for getting emails on comments :)

**Pull request merged**
