### PR TITLE
Add icon to file sidebar tabs

### PR DESCRIPTION
**Pull request by confusedguy9**
This is for Nextcloud 15 and above.

### CODE REVIEW

**Comment by confusedguy9** [comment]
Should be fine with ownCloud.

**Comment by reiner-text** [comment]
I would prefer a _summation_ icon instead of an _info_ icon. ;-)

[summation](https://en.wikipedia.org/wiki/File:Greek_uc_sigma.svg)

**Comment by Luticus** [comment]
If you're still taking suggestions on what icon should be used, I thing a hash icon (#) would make the most sense.  Because the checksums are hash values.  :)

**Comment by GuyPaddock** [comment]
Honestly, a digital fingerprint icon is probably going to be a lot more clear:

https://thenounproject.com/term/checksum/21048/

**Comment by westberliner** [comment]
Looks good. These are the basic nextcloud icons: https://docs.nextcloud.com/server/14/developer_manual/design/icons.html
I like the fingerprint variant as well. For a future version would be nice to implement.

**Comment by raoulbhatia** [comment]
👏

**Comment by reiner-text** [comment]
> I like the fingerprint variant as well. For a future version would be nice to implement.

As Nextcloud apps have more and more tabs with the _info_ icon, any other dedicated icon is welcome. 😉

**Pull request merged**
